import React from 'react';
import { 
  FileSpreadsheet, Download, Printer, CheckCircle2, TrendingUp, DollarSign, Boxes, 
  ShieldAlert, Sparkles, Award, Users, Globe2, AlertTriangle, Building, ShieldCheck
} from 'lucide-react';
import { productService } from '../services/ProductService';
import { dbService } from '../services/DatabaseService';
import { aiService } from '../services/AIService';
import { LanguageCode, CurrencyCode, UserSession } from '../types';
import { translations, formatPrice } from '../i18n/translations';
import { CountryFlag } from '../components/CountryFlag';

interface ExecutiveReportPageProps {
  userSession: UserSession;
  currentLanguage: LanguageCode;
  currentCurrency: CurrencyCode;
}

export const ExecutiveReportPage: React.FC<ExecutiveReportPageProps> = ({ userSession, currentLanguage, currentCurrency }) => {
  const t = translations[currentLanguage];
  const isFr = currentLanguage === 'fr';

  const products = productService.getAllProducts();
  const salesHistory = dbService.getSalesHistory();
  const customers = dbService.getCustomers();
  const suppliers = dbService.getSuppliers();
  const alerts = dbService.getAlertHistory().filter(a => a.status === 'Active');

  const totalValueCost = products.reduce((sum, p) => sum + (p.quantity * p.cost_price), 0);
  const totalValueSelling = products.reduce((sum, p) => sum + (p.quantity * p.selling_price), 0);
  const expectedProfit = totalValueSelling - totalValueCost;
  const nextMonthExpectedRevenue = Math.round(totalValueSelling * 0.42);

  const expiringProducts = products.filter(p => {
    const days = Math.ceil((new Date(p.expiry_date).getTime() - new Date().getTime()) / 86400000);
    return days <= 30;
  });

  const handlePrintPdf = () => {
    window.print();
  };

  const handleExportCsv = () => {
    const headers = ['Product ID', 'Product Name', 'Category', 'Quantity', 'Unit', 'Cost Price', 'Selling Price', 'Supplier', 'Destination', 'Expiry Date', 'Warehouse', 'Status'];
    const rows = products.map(p => [
      p.product_id,
      `"${p.product_name}"`,
      p.category,
      p.quantity,
      p.unit,
      p.cost_price,
      p.selling_price,
      p.supplier_country,
      p.destination_country,
      p.expiry_date,
      `"${p.warehouse}"`,
      p.status
    ]);

    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `ETS_FOFANA_Executive_Report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6 pb-12 print:bg-white print:text-black">
      {/* Header Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-800 pb-4 print:border-black">
        <div className="flex items-center space-x-3">
          <img src="/ets_fofana_logo.jpg" alt="Logo" className="h-12 w-12 rounded-xl object-cover border border-amber-500/40" />
          <div>
            <h1 className="text-2xl font-black text-white tracking-tight flex items-center space-x-2 print:text-black">
              <span>{t.reportTitle}</span>
            </h1>
            <p className="text-xs text-slate-400 mt-0.5 print:text-gray-600">
              {t.reportSubtitle} &bull; Generated by FOF-AI Platform
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-3 print:hidden">
          <button
            onClick={handleExportCsv}
            className="flex items-center space-x-2 px-3.5 py-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-200 hover:text-amber-400 text-xs font-bold shadow-sm transition"
          >
            <Download className="h-4 w-4" />
            <span>{t.exportCsv}</span>
          </button>

          <button
            onClick={handlePrintPdf}
            className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 text-xs font-bold shadow-gold-glow transition active:scale-95"
          >
            <Printer className="h-4 w-4" />
            <span>{t.printPdf}</span>
          </button>
        </div>
      </div>

      {/* SECTION 1: Summary Financial & Valuation Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="glass-card rounded-2xl p-4 border border-slate-800 space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase">{t.costValue}</span>
          <p className="text-xl font-black text-amber-400 font-mono">{formatPrice(totalValueCost, currentCurrency)}</p>
        </div>

        <div className="glass-card rounded-2xl p-4 border border-slate-800 space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase">{t.revenueValue}</span>
          <p className="text-xl font-black text-emerald-400 font-mono">{formatPrice(totalValueSelling, currentCurrency)}</p>
        </div>

        <div className="glass-card rounded-2xl p-4 border border-slate-800 space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase">{t.grossProfit}</span>
          <p className="text-xl font-black text-blue-400 font-mono">{formatPrice(expectedProfit, currentCurrency)}</p>
        </div>

        <div className="glass-card rounded-2xl p-4 border border-slate-800 space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase">{isFr ? 'Revenu Projeté Mois Prochain' : 'Expected Revenue Next Month'}</span>
          <p className="text-xl font-black text-purple-300 font-mono">{formatPrice(nextMonthExpectedRevenue, currentCurrency)}</p>
        </div>
      </div>

      {/* SECTION 2: AI CEO RECOMMENDATION & BUSINESS HEALTH SCORE */}
      <div className="glass-card rounded-2xl p-6 border border-amber-500/30 bg-gradient-to-r from-amber-500/10 via-slate-900 to-slate-950 space-y-3 shadow-xl">
        <div className="flex justify-between items-center border-b border-amber-500/20 pb-3">
          <div className="flex items-center space-x-2">
            <Sparkles className="h-5 w-5 text-amber-400" />
            <h2 className="text-sm font-extrabold text-amber-300 uppercase tracking-tight">
              {isFr ? 'Recommandation IA PDG & Score de Santé' : 'AI CEO Recommendation & Business Health Score'}
            </h2>
          </div>
          <span className="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 font-mono text-xs font-black border border-emerald-500/30">
            {isFr ? 'Score Santé : 92/100 (Bon)' : 'Health Score: 92/100 (Good)'}
          </span>
        </div>

        <p className="text-xs text-slate-200 leading-relaxed">
          {isFr ? (
            "L'IA FOF-AI recommande de donner la priorité au déstockage promotionnel des gaufrettes Atlas et biscuits Oreo expirant sous 30 jours au Mali et au Burkina Faso. Parallèlement, augmenter les commandes d'importation de Dattes Sultan Deglet Noor depuis la Tunisie en prévision du pic de demande du Ramadan."
          ) : (
            "FOF-AI recommends prioritizing promotional clearance markdown for Atlas Wafers and Oreo Biscuits expiring within 30 days across Mali and Burkina Faso. Concurrently, accelerate date import orders from Tunisia ahead of the upcoming Ramadan surge."
          )}
        </p>
      </div>

      {/* SECTION 3: TOP SELLING, SLOW MOVING & EXPIRY PRODUCTS */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Top Selling Products */}
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-3">
          <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center space-x-2">
            <Award className="h-4 w-4" />
            <span>{isFr ? 'Produits les Plus Vendus' : 'Top Selling Products'}</span>
          </h3>
          <div className="space-y-2 text-xs">
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
              <div>
                <p className="font-bold text-slate-100">Oreo Original Biscuits</p>
                <p className="text-[10px] text-slate-400">250 Cartons Sold &bull; Mali</p>
              </div>
              <span className="font-extrabold text-emerald-400">$6,500.00</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
              <div>
                <p className="font-bold text-slate-100">Sultan Deglet Noor Dates</p>
                <p className="text-[10px] text-slate-400">100 Boxes Sold &bull; Mali</p>
              </div>
              <span className="font-extrabold text-emerald-400">$4,800.00</span>
            </div>
          </div>
        </div>

        {/* Slow Moving Products */}
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-3">
          <h3 className="text-xs font-bold text-red-400 uppercase tracking-wider flex items-center space-x-2">
            <AlertTriangle className="h-4 w-4" />
            <span>{isFr ? 'Produits à Rotation Lente' : 'Slow Moving Products'}</span>
          </h3>
          <div className="space-y-2 text-xs">
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
              <div>
                <p className="font-bold text-slate-100">Bambino Fruity Gummy Candies</p>
                <p className="text-[10px] text-slate-400">35 Cartons Remaining &bull; Kayes</p>
              </div>
              <span className="font-bold text-red-400">Low Turnover</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
              <div>
                <p className="font-bold text-slate-100">Atlas Wafer Deluxe Hazelnut</p>
                <p className="text-[10px] text-slate-400">80 Cartons Remaining &bull; Kayes</p>
              </div>
              <span className="font-bold text-red-400">3 Days Remaining</span>
            </div>
          </div>
        </div>

        {/* Products Near Expiry */}
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-3">
          <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center space-x-2">
            <ShieldAlert className="h-4 w-4" />
            <span>{isFr ? 'Produits Proches de Péremption' : 'Products Near Expiry (<30 Days)'}</span>
          </h3>
          <div className="space-y-2 text-xs">
            {expiringProducts.map(p => (
              <div key={p.product_id} className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
                <div>
                  <p className="font-bold text-slate-100">{p.product_name}</p>
                  <p className="text-[10px] text-slate-400">Expires: {p.expiry_date} ({p.quantity} {p.unit})</p>
                </div>
                <span className="px-2 py-0.5 rounded bg-amber-500/20 text-amber-400 font-bold text-[10px]">
                  {p.status}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* SECTION 4: BEST CUSTOMERS & SUPPLIER PERFORMANCE */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Best Customers */}
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-3">
          <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wider flex items-center space-x-2">
            <Users className="h-4 w-4 text-blue-400" />
            <span>{isFr ? 'Meilleurs Clients VIP (CRM)' : 'Best Customers (CRM)'}</span>
          </h3>
          <div className="space-y-2 text-xs">
            {customers.slice(0, 3).map(c => (
              <div key={c.customer_id} className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
                <div>
                  <p className="font-bold text-slate-100">{c.company_name}</p>
                  <p className="text-[10px] text-slate-400 flex items-center space-x-1">
                    <CountryFlag countryName={c.country} className="h-3 w-4 inline mr-1" />
                    <span>{c.country} &bull; {c.total_orders} Orders</span>
                  </p>
                </div>
                <span className="font-extrabold text-emerald-400">{formatPrice(c.total_spent, currentCurrency)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Supplier Performance */}
        <div className="glass-card rounded-2xl p-5 border border-slate-800 space-y-3">
          <h3 className="text-xs font-bold text-purple-400 uppercase tracking-wider flex items-center space-x-2">
            <Globe2 className="h-4 w-4 text-purple-400" />
            <span>{isFr ? 'Performance des Fournisseurs' : 'Supplier Performance & Reliability'}</span>
          </h3>
          <div className="space-y-2 text-xs">
            {suppliers.map(s => (
              <div key={s.supplier_id} className="p-3 rounded-xl bg-slate-900 border border-slate-800 flex justify-between items-center">
                <div>
                  <p className="font-bold text-slate-100">{s.supplier_name}</p>
                  <p className="text-[10px] text-slate-400">
                    <CountryFlag countryName={s.country} className="h-3 w-4 inline mr-1" />
                    {s.country} &bull; Lead Time: {s.lead_time_days} Days
                  </p>
                </div>
                <span className="px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 font-bold text-[10px]">
                  ⭐ {s.rating} / 5.0
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* SECTION 5: MASTER INVENTORY AUDIT SHEET TABLE */}
      <div className="glass-card rounded-2xl p-6 border border-slate-800 shadow-xl space-y-4">
        <h2 className="text-sm font-bold text-amber-400 uppercase tracking-wider flex items-center space-x-2">
          <Building className="h-4 w-4 text-amber-400" />
          <span>{t.masterAuditTitle}</span>
        </h2>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 uppercase font-bold text-[10px]">
                <th className="py-3 px-3">ID</th>
                <th className="py-3 px-3">{t.productName}</th>
                <th className="py-3 px-3">{t.category}</th>
                <th className="py-3 px-3">{t.originMarket}</th>
                <th className="py-3 px-3">{t.qtyUnit}</th>
                <th className="py-3 px-3">Unit Cost</th>
                <th className="py-3 px-3">Unit Price</th>
                <th className="py-3 px-3">{t.expiryDate}</th>
                <th className="py-3 px-3">{t.warehouse}</th>
                <th className="py-3 px-3">{t.status}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 font-medium">
              {products.map((p) => (
                <tr key={p.product_id} className="hover:bg-slate-900/60 transition">
                  <td className="py-3 px-3 text-slate-400 font-mono">#{p.product_id}</td>
                  <td className="py-3 px-3 font-bold text-slate-100">{p.product_name}</td>
                  <td className="py-3 px-3 text-slate-300">{p.category}</td>
                  <td className="py-3 px-3">
                    <span className="flex items-center space-x-1">
                      <CountryFlag countryName={p.supplier_country} className="h-3 w-4 inline mr-1" />
                      <span>{p.supplier_country}</span>
                      <span>&rarr;</span>
                      <CountryFlag countryName={p.destination_country} className="h-3 w-4 inline mr-1" />
                      <span>{p.destination_country}</span>
                    </span>
                  </td>
                  <td className="py-3 px-3 font-bold text-amber-400">{p.quantity} {p.unit}</td>
                  <td className="py-3 px-3 text-slate-300">${p.cost_price.toFixed(2)}</td>
                  <td className="py-3 px-3 font-bold text-emerald-400">${p.selling_price.toFixed(2)}</td>
                  <td className="py-3 px-3 text-slate-300 font-mono">{p.expiry_date}</td>
                  <td className="py-3 px-3 text-slate-300">{p.warehouse}</td>
                  <td className="py-3 px-3">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      p.status === 'In Stock' ? 'bg-emerald-500/20 text-emerald-400' :
                      p.status === 'Approaching Expiry' ? 'bg-amber-500/20 text-amber-400' : 'bg-red-500/20 text-red-400'
                    }`}>
                      {p.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
